empty = " "
black = "B"
white = "W"
n = 1
NEG_INF = -1000000000
POS_INF = 1000000000
recv_size_player = 8192  # amount we can receive at a time (pseudo arbitrary)
crazy = "GO has gone crazy!"
history = "This history makes no sense!"
bananas = "I am going bananas!"
maxIntersection = 4
no_name = "no name"
